
[Timers]
	#Modify the timers for the surface (to reduce or increase them), based on the general timer set (e.g. spawn timer of 300 seconds -> 0.3 turns it into 90 seconds and 1.7 turns it into 510 seconds for the surface)
	#Range: 0.0 ~ 5.0
	surface_timer_multiplier = 1.0

	[Timers.Spawn]
		#Minimum time between spawns in seconds
		#Range: 0 ~ 86400
		can_spawn_min = 400
		#Maximum time between spawns in seconds
		#Range: 0 ~ 86400
		can_spawn_max = 800
		#Chance for a spawn cooldown to occur
		#Range: 0.0 ~ 1.0
		can_spawn_cooldown_chance = 0.05
		#Spawn cooldown length in seconds
		#Range: 0 ~ 86400
		can_spawn_cooldown = 1200

	[Timers.Noise]
		#Minimum time between noise occurrences in seconds
		#Range: 0 ~ 86400
		reset_noise_min = 340
		#Maximum time between noise occurrences in seconds
		#Range: 0 ~ 86400
		reset_noise_max = 460

	[Timers.Leave]
		#Time (in seconds) it takes for the GoatMan to leave
		#Range: 1 ~ 6000
		time_until_leave = 200
		#Time (in seconds) it takes for the GoatMan to leave once a chase begins
		#Range: 1 ~ 600
		time_until_leave_chase = 25

["Spawn Conditions"]
	#The spawn chance per tick (once the spawn timer is finished)
	#Range: 0.0 ~ 1.0
	spawn_chance_per_tick = 0.05
	#Depth at which the GoatMan can start to spawn
	spawn_height = 500
	#Whether the GoatMan can spawn on the surface or not
	allow_surface_spawn = true
	#The maximum sky light level the GoatMan can spawn at
	#Range: 0 ~ 15
	sky_light_level = 14
	#The maximum block light level the GoatMan can spawn at
	#Range: 0 ~ 15
	block_light_level = 14
	#The maximum amount of GoatMan which can exist at the same time
	#Range: 0 ~ 100
	maximum_amount = 2
	#How close to players the GoatMan is allowed to spawn (in blocks)
	#Range: 0 ~ 64
	spawn_distance = 18
	#If set to true the GoatMan will try to find a spawn position with a possible path to the player
	check_path_to_spawn = true

	["Spawn Conditions".Dimensions]
		#The dimensions where the GoatMan can spawn in (Whitelist)
		dimension_whitelist = ["minecraft:overworld"]

	["Spawn Conditions".Biomes]
		#If you don't want to create a datapack to configure the biomes
		override_biome_datapack_config = true
		#Use the surface biome list either as white- or blacklist
		surface_biomes_is_whitelist = false
		#Either white- or blacklist of the surface biomes the GoatMan can spawn in (Syntax: modid:biome, e.g. `minecraft:plains`)
		surface_biomes = ["minecraft:desert", "minecraft:badlands", "minecraft:eroded_badlands", "minecraft:wooded_badlands", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:windswept_savanna", "minecraft:mangrove_swamp"]

[Behaviour]
	#The distance in blocks at which the GoatMan can detect whether a player is looking at it or not
	#Range: 0 ~ 128
	spotting_range = 100
	#Whether the GoatMan can climb or not
	can_climb = true
	#Allow the GoatMan to follow vanilla riding logic (e.g. boats)
	allow_riding = false
	#Whether invisible players can be targets or not
	target_invisible = false

[Attributes]
	#Maximum Armor
	#Range: 0.0 ~ 20.0
	maximum_armor = 20.0
	#Maximum Health
	#Range: 1.0 ~ 500.0
	maximum_health = 100.0
	#Attack Damage
	#Range: 0.0 ~ 50.0
	attack_damage = 5.0
	#Movement Speed
	#Range: 0.0 ~ 5.0
	movement_speed = 0.6
	#Depth Strider (movement speed in water) Bonus
	#Range: 0.0 ~ 3.0
	depth_strider_bonus = 2.0

[Misc]
	#Only play the ambient noises to the current (spawn) target (Note: The target can change when a spawn attempt is not successful)
	only_play_noise_to_target = false

